# Generated by Django 5.2.9 on 2025-12-25 11:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('registration_number', models.CharField(help_text='Business registration number.', max_length=100, unique=True)),
                ('tax_pan_number', models.CharField(max_length=50, unique=True)),
                ('garage_type', models.CharField(choices=[('auto-repair', 'Auto Repair'), ('body-shop', 'Body Shop'), ('multi-service', 'Multi-Service')], max_length=20)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('working_hours', models.JSONField(blank=True, help_text="Example: {'mon-fri': '9am-6pm', 'sat': '10am-4pm'}", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('labor_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garages.garage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
